import { Nav } from "@/src/Nav"
import Head from 'next/head'
import '@/styles/common.scss';
import '@/styles/add_post.scss';

export default function App({ Component, pageProps }) {
  return <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <Nav />
          <Component {...pageProps} />
        </>
}
