import Head from 'next/head'

const HeadMeta = () => {
    return (
        <Head>
            <title> 본스케치 </title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}

export default HeadMeta